window.I18N = window.I18N || {};
window.I18N.en = {
  common: { skip: '', homeSuffix: '', ready: '', details: '', all: '', newWindow: '' }, // TODO[T1]
  nav: { home: '', schedule: '', boarding: '', terminal: '', customer: '' }, // TODO[T1]
  terminalNav: { terminalInfo: '', introduction: '', facilities: '', directions: '', operation: '', arrivals: '', timetable: '', fare: '', routes: '', weather: '', operators: '', operatorGuide: '', shipGuide: '', boarding: '', process: '', identity: '', baggage: '', vehicle: '', safety: '', customer: '', notices: '', faq: '', lostFound: '', tourism: '' }, // TODO[T3]
  portalNav: { terminal: '', allTerminals: '', mapSearch: '', operation: '', arrivals: '', timetable: '', routes: '', weather: '', booking: '', ticket: '', fare: '', events: '', refund: '', boarding: '', process: '', identity: '', baggage: '', vehicle: '', safety: '', customer: '', notices: '', faq: '', inquiryBoard: '', lostFound: '' }, // TODO[T2]
  header: { mainMenu: '', mobileDetail: '', quickMenu: '', allTerminals: '', mobileTerminal: 'Terminal', terminalHomepage: '', allMap: '', language: 'Language', korean: 'Korean', english: 'English', search: '', menuOpen: '', menuClose: '', network: '' }, // TODO[T1]
  mega: { intro: '', realtime: '', plan: '', cancellation: '', process: '', identity: '', baggage: '', vehicle: '', directions: '', facilities: '', parking: '', notices: '', faq: '', lostFound: '', inquiry: '' }, // TODO[T1]
  footer: { phone: '', privacy: '', terms: '', sitemap: '', directions: '', allTerminals: '', slogan: '' }, // TODO[T1]
  terminalPage: { heroButton: '', quickAria: '', timetable: '', timetableDesc: '', fare: '', fareDesc: '', boarding: '', boardingDesc: '', directions: '', directionsDesc: '', boardingTitle: '', boardingMore: '', notices: '', noticeAll: '', allView: '', customer: '', customerHelp: '', counselingHours: '', infoSuffix: '', address: '', hours: '', parking: '' }, // TODO[T3]
  schedule: { movementAria: '', departure: '', arrival: '', terminalFilterAria: '', all: '', routeFilterAria: '', routeType: '', oneWay: '', circular: '', expand: '', collapse: '', legendAria: '', status: { normal: '', delayed: '', cancelled: '', controlled: '', inquiry: '' } }, // TODO[T1]
  ports: { jeju: '', chuja_wando: '', wando: '', mokpo: '', samcheonpo: '', chuja_jindo: '', nokdong: '', chuja_from_jindo: '', chuja_from_wando: '' }, // TODO[T1]
  facilities: { waitingRoom: '', nursing: '', store: '', restaurant: '', locker: '', wifi: '', accessibility: '', lostFound: '' }, // TODO[T1]
  portalSubpage: { description: { terminal: '', map: '', schedule: '', arrivals: '', timetable: '', routes: '', weather: '', booking: '', fare: '', refund: '', boarding: '', process: '', identity: '', baggage: '', vehicle: '', safety: '', customer: '', notices: '', faq: '', inquiry: '', lostFound: '' }, bookingLink: '', bookingLead: '', farePending: '', fareAlternative: '', refundPending: '', refundAlternative: '', safetyPending: '', safetyAlternative: '', preparing: '', routesRegion: '', routesTerminal: '', routesTable: '', noRoutes: '' }, // TODO[T4]
  portal: { metaTitle: '', metaDescription: '', heroTitle1: '', heroTitle2: '', heroDescription1: '', heroDescription2: '', heroPicker: '', heroSlide1: '', heroSlide2: '', heroSlide3: '', heroPrevious: 'Previous hero image', heroNext: 'Next hero image', heroPlay: 'Play hero slides', heroPause: 'Pause hero slides', quickAria: '', quickTitle: 'Passenger Smart Service', quickDescription: 'Quick access to essential passenger ferry services.', findTerminal: '', findTerminalDesc: '', schedule: '', scheduleDesc: '', bookingQuick: '', bookingQuickDesc: '', boarding: '', boardingDesc: '', customer: '', customerDesc: '', networkTitle: '', networkDescription: '', mapAria: '', select: '', selected: '', location: '', phone: '', routes: '', operators: '', operatorHomepage: '', hours: '', terminalCount: '', preCheckTitle: '', preCheckText1: '', preCheckText2: '', sourceLabel: '', servicesAria: '', routeCaption: '', routeName: '', duration: '', frequency: '', routePending: '', operatingHours: '', typeFilterAria: '', type: { coastal: '', ocheon: '', international: '', cruise: '', expo: '', pohang: '', ulleung: '', ulleungDodong: '', ulleungSadong: '', ulleungJeodong: '', yeongdoCruise: '', heuksando: '', hongdo: '', jindo: '', ttangkkeut: '', seogwipo: '', nokdong: '', narodo: '', geomundo: '', samcheonpo: '', sokcho: '', mukho: '', dock: '' }, todaySchedule: '', terminalGuide: '', useGuide: '', transit: '', transitDesc: '', facilities: '', facilitiesDesc: '', homepage: '', guideTitle: '', guideIdTitle: '', guideIdText: '', guideVehicleTitle: '', guideVehicleText: '', guideBaggageTitle: '', guideBaggageText: '', guideParkingTitle: '', guideParkingText: '', bottomInfoAria: '', latestNotices: '', viewAllNotices: '', featuredNoticeTitle: '', featuredNoticeText: '', notice1: '', notice2: '', notice3: '', notice4: '', notice5: '', notice6: '', notice7: '', bookingSectionTitle: '', bookingEyebrow: '', bookingTitle: '', bookingText: '', bookingButton: '' } // TODO[T2]
};
